version: "3.3"

services:
  proxy:
    env_file:
      - ./config/local/.env
    volumes:
      - "./config/local/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - backend
  
  backend:
    env_file:
      - ./config/local/.env
    volumes:
      - "./backend:/app"
    build:
      dockerfile: "Dockerfile.local"
    ports:
      - "8080:8080"
      - "9229:9229"
    depends_on:
      - db

  pgadmin:
    env_file:
      - ./config/local/.env

  db:
    env_file:
      - ./config/local/.env
    volumes:
      - "db-local:/var/lib/postgresql/data"

volumes:
  db-local:
